### ISSUE TITLE
ToastNotifications not working for Release build

### ISSUE THREAD

**Issue by BerndNK** [grollmus/BuildNotifications#125]
No ToastNotifications are shown for the Release version of BuildNotifications

**Comment by BerndNK** [comment]
Something weird is happening in the current Release build. The plugin not loading, builds are not updating and overall performance is horrible. Further investigation is needed.

**Comment by TheSylence** [comment]
The horrible performance happens after openeing the info popup.
Maybe this is related to the blur effect?

**Comment by BerndNK** [comment]
Created #127 for performance issue

**Comment by BerndNK** [comment]
The Plugin can't be loaded as the NotificationProcessor Type from the plugin is not assignable to the interface. This DOES work in Visual Studio, however not in the GitHub build.

See 
2020-02-11 11:03:51.1342 BuildNotifications.Core.Plugin.PluginLoader+<LoadPluginsOfType>d__5`1 Type BuildNotifications.PluginInterfacesLegacy.Notification.INotificationProcessor is not assignable from ToastNotificationsPlugin.ToastNotificationProcessor

**Comment by BerndNK** [comment]
This will work when the PluginInterfaces.Legacy.dll from the plugins/toast folder is moved to the root folder (and replaced).

So it seems that during the build the ToastNotificationPlugin is using a different Interface.dll than the BuildNotifications.exe

**Comment by TheSylence** [comment]
"Fixed" this by moving the PluginInterfaces.Legacy.dll during the release process to the correct location.
