### ISSUE TITLE
Fody

### ISSUE THREAD

**Issue by TheSylence** [grollmus/BuildNotifications#130]
Anotar.NLog.Fody is the only Fody dependency that is left.
It prevents Edit & Continue 99% of the time.

Either fix this or remove fody all together and replace the LogTo class with something custom built.

**Comment by TheSylence** [comment]
The latest Visual Studio update provides a more detailed error message when trying to edit and continue:

> CS7038 Failed to emit module 'BuildNotifications.Plugin.Tfs': Changing the version of an assembly reference is not allowed during debugging: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' changed version to '2.1.0.0'.

**Comment by BerndNK** [comment]
This issue got more critical as it currently causes issues when releasing a new version:
![image](https://user-images.githubusercontent.com/7613199/83629971-543cb500-a59b-11ea-8eb8-d71a9bd1c825.png)
