### ISSUE TITLE
Batch multiple changes to TreeItems into one CollectionChangedEvent to improve performance

### ISSUE THREAD

**Issue by BerndNK** [grollmus/BuildNotifications#138]
When displaying many builds in one collection and the collection is changed, each add/remove triggers a single event causing multiple properties to be set and the view to be redrawn.

One add - one event is required for WPF, as WPF cannot handle batched adds and removes. However our own code can be modified. Specifically the
BuildTreeNodeViewModel.OnChildrenChanged method.
 
![image](https://user-images.githubusercontent.com/7613199/76077626-5b0a5a80-5fa1-11ea-976b-652fa45f3be4.png)

Therefore the proposed solution is to add a second CollectionChanged event "CollectionChangedBatched" which is used internally to handle these batch changes and reduce the impact on WPF.

**Comment by BerndNK** [comment]
I'm thinking about closing this issue, as (if I'm reading it correctly) .Net 5.0 will support AddRange methods within ObservableCollection. Along with (finally!!!) WPF support for CollectionChanged events with multiple items.
https://github.com/dotnet/runtime/issues/18087

So we could just wait until November for this. Currently my implementation is not that much faster, as WPF is still the bottleneck arranging over and over again when many builds are removed/added.

That is, IF the issue stays within the 5.0 milestone and gets resolved. What do you think @TheSylence?

**Comment by TheSylence** [comment]
The PR that extends the Collection API has already been merged however WPF doesn't seem to care that much https://github.com/dotnet/wpf/issues/52

IF WPF 5 will support the new API there is no need to fix this at our end.

**Comment by BerndNK** [comment]
Interesting enough, there seems to be a duplicate planned for 5.0?
https://github.com/dotnet/wpf/issues/1887

**Comment by BerndNK** [comment]
I'll close this until we know more.
