### ISSUE TITLE
Retry connecting on initial start

### ISSUE THREAD

**Issue by BerndNK** [grollmus/BuildNotifications#153]
The current behavior of BN is to stop auto-updating as soon as any provider throws an error.
This is fine, however during the initial start, I'd propose a different solution.

Especially in use cases where the user first has to connect to a VPN, the established provider cannot be connected to successfully. Therefore the user will always have to restart the update process.

I'd suggest to have a automatic retry feature, when no builds have ever successfully loaded and BN is still running in the background.

**Comment by TheSylence** [comment]
The current version works when starting the DummyBuildServer after BN but fails when using DevOps without VPN.
Worst of all you now have to restart BN after connecting to VPN.

**Comment by TheSylence** [comment]
Okay you don't have to restart BN but have to manually trigger a refresh by opening the settings and clicking "close and resume".
After this the refresh works as expected.

**Comment by BerndNK** [comment]
Still not ideal 😂

**Comment by TheSylence** [comment]
Okay this still isn't fixed. The problem seems to be that the Devops plugin tries to do some queries when loaded and this fails thus the proejct won't be loaded at all.

Either fix the Devops plugin or try to load projects more than once.
