### ISSUE TITLE
Verbose logging

### ISSUE THREAD

**Issue by BerndNK** [grollmus/BuildNotifications#19]
The logs should be written to a file.
On top of that, the current build should be enhanced with various logging messages throughout the code to ensure strong debugging capabilities in the future.

**Comment by BerndNK** [comment]
Implemented a great part of this in 332f7805369709ea555a2c6f6b31ba9c65859f41

**Comment by TheSylence** [comment]
We need a guideline on how to decide if and when to use the different log levels:
- Trace
- Debug
- Info
- Warning
- Error
- Fatal

**Comment by BerndNK** [comment]
I suppose:
- Trace
  - Unused
- Debug
  - I'd use this as the replacement for trace. Publish debug messages everywhere it seems fit. "Fetched 3 new builds from {Plugin}", "grouping changed", "Update took n seconds". Etc.
- Info
  - Unused. I don't see a point in notifying the user when something is not particularly bad, in which case I'd treat it as a warning. For notifying the developer I'd use the Debug level.
- Warning
  - Everything that is out of the ordinary and could potentially be interesting to the user. E.g. "No configuration file was found, default used."
- Error
  - Breaking but somewhat expected errors that should definitely be relevant to the user. E.g. a plugin failed to load. An error during an update etc.
- Fatal
  - Unexpected errors. Globally unhandled exceptions which, ideally, should never occur.

Which results in the logging of:
**Debug:** Debugger console output
**Warning:** Debugger console output, Log file
**Error:** Debugger console output, Log file, direct notification within the app
**Fatal:** Debugger console output, Log file (output within the app is not possible, as fatal errors crash the app)

So in order to close the issue:

- Setup Debug Console log output
- Setup Log file output
- Setup global exception handler
- Add various Debug log messages
- Investigate and add warning messages

What do you think?

**Comment by BerndNK** [comment]
Clarification:
For debug I want everything that is probably the developers fault. E.g. an exception because a resource string was not found. Something is not implemented.

For warning I want everything that has any other form of issue. Settings are screwed, server is not responding, user has no privileges. 

Everything that is not catched by Debug, will be fatal anyway.

**Comment by BerndNK** [comment]
By that logic, for example, in PluginRepository every log should be of level Warn. As this could fail for corrupt configuration or wrong implementation. And since configuration is treated as user input, this should be something the user should be notified about.

One could argue that these could also be errors.

**Comment by TheSylence** [comment]
I would propose to use the Info level to log the program flow. This way we can see what happened before something goes wrong. 
These messages would never be shown to the user directly but only be logged to file.

Since NLog can be configured by file I suppose we can simply deploy a default config that would not write debug (and maybe even info) to file.
Then when debugging an issue this configuration can be modified to write more verbose messages to file.

I don't want the user to have several dozens of megabytes of log files on his system unless they explicitly configured the logger to do so.

**Comment by BerndNK** [comment]
I'm not sure what the specific difference between Info and Debug is?
Provide an example of when to use Info and when to use Debug?

**Comment by TheSylence** [comment]
I'd say info is just a simple "now doing this" and debug "and while doing so I have this data and doing that thing with them"

So something like
> Info: Loading Plugins
> Debug: Searching Plugins/A for Plugin files
> Debug: Found Plugin.dll
> Debug: Plugin.dll contains 1 Source Control Provider and 2 Build Providers
> Debug: Searching Plugins/B for Plugins files
> ...
> Info: Loaded 4 plugins

**Comment by BerndNK** [comment]
Alright. I agree this makes sense. We can implement it that way.

**Comment by BerndNK** [comment]
Implemented a lot in 79f089d83e9c16dd074005aedda3238d1c49df85.
Including Pipeline/Update-cycle/Notifications/Plugins/Storing and loading configurations

Are there any other parts of the tool you specifically want to be logged @TheSylence ?

Otherwise I'd close the issue, as surely logging is an ongoing, parallel task.

**Comment by TheSylence** [comment]
Looks and sounds good
