### ISSUE TITLE
Uninitialized NotificationProcessor

### ISSUE THREAD

**Issue by TheSylence** [grollmus/BuildNotifications#244]
When the processor throws an exception while being initialized it is still added to the Distributor.
I'd say we should not add a potentially broken processor to the distributor?

https://github.com/grollmus/BuildNotifications/blob/5c6d0ae5967950450a8d48e4299ed44f69cf52d0/BuildNotifications.Core/Pipeline/Notification/Distribution/BaseNotificationDistributor.cs#L56-L71

**Comment by BerndNK** [comment]
You're right. I believe this is an oversight and should be fixed
