### ISSUE TITLE
Implement Blacklist and Whitelist

### ISSUE THREAD

**Issue by TheSylence** [grollmus/BuildNotifications#29]
I want to be able to configure which branches and/or BuildDefinitions I want to be notified about.

**Comment by BerndNK** [comment]
Whitelists have a higher priority than blacklists.
The option "Exclusively load whitelist" will be redundant.

The same functionality can be achieved by:
- Setting an entry on the blacklist to "*"
- Setting any entry on the whitelist to the desired items. E.g. "stage"

The blacklist will exclude everything, but the whitelist will then include stage again.

The other way around makes no sense, as by default everything is included.


Filtering features:
- Lists feature wildcards '*'
- Exact match is implied
- Parenthesis express case sensitivity

Example:
Suppose two names:
1. "ABCDE"
2. "bC"

> BC

 will filter 2.
> "BC" 

will filter none
> *BC*

will filter both.
>"bC"
will filter 2.
> "ABC

will filter none. -> Invalid syntax, the single " is searched within the strings.
> AB*E

will only filter 1.
> "ab"*"a"

will filter none. -> case doesn't match
> *DE

will only filter 1.
>"C"

will filter none.

**Comment by BerndNK** [comment]
Changed the requirements a bit.
Wildcards now implied. An = at the start of the search term implies an exact match.
View StringMatcherTests for more details.

This change was made for better user experience. This behavior is now consistent with the previous search bar functionality, which now also uses the StringMatcher. Bringing support for wildcards * and optional case-sensitivity with quotation marks "".
