### ISSUE TITLE
Build failed: It doesn't match the target delegate 'CancelEventHandler'

### ISSUE THREAD

**Issue by appcoampatTest** [grollmus/BuildNotifications#342]
Application Name: BuildNotifications
OS: Windows 10
CPU: X64
.NET Build Number: 6.0.100-rc.1.21425.10

I want to build this app but It failed.
**There is an Excepiton in MainWindow.xaml.cs(Line:16)**
![image](https://user-images.githubusercontent.com/70257318/131621215-5262ea1e-4b0f-4651-965c-2659b47637e1.png)

I think it about Nullability of reference types.

**Comment by TheSylence** [comment]
I fixed this specific issue but we currently only support .NET 5.
I will port the application once .NET 6 is final (so around November 2021)
