### ISSUE TITLE
Plugin API considerations

### ISSUE THREAD

**Issue by TheSylence** [grollmus/BuildNotifications#41]
Before declaring the API as 1.0 some decisions have to be made:
- How many concurrent versions of the API should be supported? 
  - More than one would require to host plugins in separate processes.
- How to make sure there are as few breaking changes in the future as possible?
  - Provide abstract classes instead of interfaces so future functions can have default implementations?
  - Create new interfaces when adding new functionality? (i.e. IPlugin1, IPlugin2, ... IPluginN)

**Comment by BerndNK** [comment]
> How many concurrent versions of the API should be supported?
More than one would require to host plugins in separate processes.

I'm fine with making breaking changes. If you don't want to update your plugin, don't update the tool. At the same time I don't expect too many breaking changes.

> Provide abstract classes instead of interfaces so future functions can have default implementations?

There is a new C#8 feature for that -> default implementations for interfaces

> Create new interfaces when adding new functionality? (i.e. IPlugin1, IPlugin2, ... IPluginN)

Maybe in some rare cases? Although I think most should be solvable with the interface default implementations.
