### ISSUE TITLE
Handle passwords in configuration

### ISSUE THREAD

**Issue by TheSylence** [grollmus/BuildNotifications#45]
Passwords are stored in plain text.

I propose to use the DPAPI to encrypt sensible configuration data with the user's/machine's credentials.

**Comment by BerndNK** [comment]
To complete this

- Delete plain text Password of TfsConfiguration
- Rename (to just Password) and use SecurePassword property of TfsConfiguration
- Write custom JSON Parser for SecureString and implement mentioned encryption method
