### ISSUE TITLE
Enhanced PullRequest features

### ISSUE THREAD

**Issue by BerndNK** [grollmus/BuildNotifications#77]
PullRequest Name-Display-Option:
- "PR [Number" (current implementation)
- Name of PR
- Merge path. E.g. "Branch A -> Branch B"

Display own icon for PullRequests

**Comment by TheSylence** [comment]
Option is implemented and text is shown accordingly.
What's left is a flag at a BranchTreeNode that indicates whether the branch is a PR so we can display a different icon.

**Comment by BerndNK** [comment]
Theres also still an issue, when switching the setting after the first initial load is already done.
-> Setting on "Number"
-> Restart BN and let builds load
-> Change setting of project to "Name"
-> Exceptions occur and the PR's aren't displayed

**Comment by BerndNK** [comment]
Also for notifications there should be a different wording when builds a grouped by "branch". If it's a pull request it should state "Pull Request failed"

**Comment by BerndNK** [comment]
I consider this issue to be done. Followup for notifications created #124
