### ISSUE TITLE
Text in toast notifications is cut off

### ISSUE THREAD

**Issue by TheSylence** [grollmus/BuildNotifications#78]
![image](https://user-images.githubusercontent.com/5342047/66293193-679d6080-e8e6-11e9-805a-e9e4540a088a.png)

**Comment by BerndNK** [comment]
Welp, so much for DPI scaling.
How many DPI does your monitor have?

**Comment by TheSylence** [comment]
Windows is set to 150% scaling on this display.
DPI? No idea. It's a 3840x2160 resolution.
