### ISSUE TITLE
Branches are used by all source provider

### ISSUE THREAD

**Issue by BerndNK** [grollmus/BuildNotifications#84]
Suppose one build provider with a list of branches (A, B and C)
These branches however are divided into two repositories. RepoA and RepoB.

RepoA has A and B, while RepoB has C.

With one connection/project with RepoA, only the branches A and B are shown. (As builds for branch C are hidden, as the branch C cannot be found)

Analog to RepoB.

However if two connections with two projects are setup, all branches get thrown into one bucket. So all builds are shown twice. Once for RepoA and RepoB.

**Comment by TheSylence** [comment]
Is this still an issue? The branch instances are fetched from the project's branch provider during build enrichment.
They should never get mixed up with branches from different projects.

**Comment by TheSylence** [comment]
Added a test to verify everything is separated correctly. Or am I missing something?

**Comment by BerndNK** [comment]
Indeed I believe this issue has been fixed with the settings refactoring. The previous use case I had, which lead me to this bug, is no longer an issue. I'm closing it.
