### ISSUE TITLE
Grouping button broken

### ISSUE THREAD

**Issue by TheSylence** [grollmus/BuildNotifications#88]
BN is set to start minimized with windows. Opening the window for the first time takes a long time and the grouping button is broken.

Broken as in: The icon is missing and clicking on it does not open the popout.

Restarting the app fixes this.

![image](https://user-images.githubusercontent.com/5342047/67187117-d354f280-f3e9-11e9-9ff4-6b56c6b965a7.png)

**Comment by TheSylence** [comment]
Maybe this is related to #74 ?

**Comment by TheSylence** [comment]
Another thing I noticed is when this happens I get a hand cursor when hovering the marked areas whit the mouse.

Clicking at these spots randomly opens one of the grouping and sorting sub menus

![image](https://user-images.githubusercontent.com/5342047/75010868-8c9e0480-547e-11ea-8d39-a5efc8e0b5af.png)

**Comment by TheSylence** [comment]
Not only occuring on my machine but on at least two others as well :(

**Comment by BerndNK** [comment]
I have this occurring on my machine now. Still have no idea why this happens though.
